[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"